### ISSUE TITLE
Finish the exercise!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/m2-evaluacion-intermedia-patriciaSR#1]
Really cool job @patriciaSR  !!!

Here you have some tips to improve the exercise:

### JavaScript

- [x] Remember to convert input value string to a number
- [x] On page load, execute 'getRandomNumber' function and store the returned value on a constant to work with it later.
- [x] If you call 'getRandomNumer' function inside the event callback, you will be creating a new random number each time the user clicks the button. That makes the game really complex and the hints will not have sense. Let's generate the random number when the page loads instead.

### Further challenges

Then you can improve the game as you please, here you have some ideas:

- Add new feedback when the number is bigger than 100 or smaller than 0.
- Manage when the user hits the button and the input is empty.
- Make the input work when hitting enter key.
- Add a reset button that cleans the input, the counter, writes the initial feedback and generates a new random number to play again!
- Whatever you want!

### Call to action

Let me know if you have any doubts ;)

Go for it!!

**Comment by patriciaSR** [comment]
Fixed and improved in master! 
Thanks for your tips to improve the exercise :)
